# Generated by Django 4.2.5 on 2023-10-05 19:52

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Bug",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("description", models.TextField()),
                (
                    "bug_type",
                    models.CharField(
                        choices=[
                            ("error", "Error"),
                            ("feature", "New Feature"),
                            ("enhancement", "Enhancement"),
                            ("other", "Other"),
                        ],
                        max_length=20,
                    ),
                ),
                ("report_date", models.DateField(auto_now_add=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("to_do", "To Do"),
                            ("in_progress", "In Progress"),
                            ("done", "Done"),
                        ],
                        max_length=20,
                    ),
                ),
            ],
            options={
                "ordering": ["-report_date"],
            },
        ),
    ]
